// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDymDq6YRSfPpIiz20o6ErPIxOazerD25Q',
    appId: '1:1084276995010:web:f8bef0730d868bc6639c5b',
    messagingSenderId: '1084276995010',
    projectId: 'bitcoin-app-4629a',
    authDomain: 'bitcoin-app-4629a.firebaseapp.com',
    storageBucket: 'bitcoin-app-4629a.appspot.com',
    measurementId: 'G-HNZSDMGSLP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0P1BudIBFqcWI0G0pxcFGLnf3Wj1bhsw',
    appId: '1:1084276995010:android:71c7597df336dc86639c5b',
    messagingSenderId: '1084276995010',
    projectId: 'bitcoin-app-4629a',
    storageBucket: 'bitcoin-app-4629a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2fIKwvEUXo90v3fQy5yy9qY8soXKOANA',
    appId: '1:1084276995010:ios:ca1996583b29fa0d639c5b',
    messagingSenderId: '1084276995010',
    projectId: 'bitcoin-app-4629a',
    storageBucket: 'bitcoin-app-4629a.appspot.com',
    iosBundleId: 'com.example.bitcoinapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2fIKwvEUXo90v3fQy5yy9qY8soXKOANA',
    appId: '1:1084276995010:ios:ca1996583b29fa0d639c5b',
    messagingSenderId: '1084276995010',
    projectId: 'bitcoin-app-4629a',
    storageBucket: 'bitcoin-app-4629a.appspot.com',
    iosBundleId: 'com.example.bitcoinapp',
  );
}
